### ISSUE TITLE
Thumbnail sizes and shapes issues

### ISSUE THREAD

**Issue by DBinaghi** [omeka/theme-foundation-classic#20]
In `items/browse`, thumbnails appear to have different sizes: fallback thumbnails are smaller, document thumbnails are bigger; same size (small one) for all would be better.
In `items/show`, PDF thumbnails never appear to be squared, no matter which option for Media Display one chooses: PDF show up as medium sized rectangular embed divs.

**Comment by kimisgold** [comment]
There is now the "Default Thumbnail Size" setting for selecting which thumbnail type to display on the browse views. Selecting the "square thumbnail" option should give you consistent thumbnail sizes for all file types.

The thumbnails on the show views are managed in the "Media Display" setting and have been adjusted to use the correct square thumbnails for PDFs, used in the "list" and "grid" options.
