### ISSUE TITLE
Thumbnail not aligned in Items/Show, Revolution theme

### ISSUE THREAD

**Issue by DBinaghi** [omeka/theme-foundation-classic#22]
Thumbnail is not aligned with the other metadata content, probably because of some margin-left value not 0.

Besides (but not necessarily a problem): when selecting Bottom for Media position, I would expect the thumbnails to be at the bottom; insted, they're above tags, quotation and even Social Bookmarking.

Theme: Revolution
Media position: Bottom

**Comment by kimisgold** [comment]
The margin issue should now be fixed.

The "bottom" position really places the files embedded within the flow of the metadata, positioned where it appears within the default core views. It's an easier label than "Embedded in metadata", but I'm open to a better name for the option.

**Comment by DBinaghi** [comment]
I see your point. But I personally find it less confusing if it's completely at the top or completely at the bottom. So, what about adding an extra option? The middle one could be just "Embedded".

**Comment by DBinaghi** [comment]
The extra option is good, but when selecting Bottom the label "File" has disappeared, and the thumbnail is not aligned with the other metadata. (not sure whether it is intentional or not, just doesn't look too neat)
