### ISSUE TITLE
Multiple values for same field displayed a bit confusingly

### ISSUE THREAD

**Issue by DBinaghi** [omeka/theme-foundation-classic#24]
Now, if Display Metadata Values Online option is checked, then multiple values get correctly stacked, and separated by a thin line.
Suggestion: change color of that line to something more neutral, because with Search By Metadata plugin enable values become links and therefore red, and the line is also reddish so it's a bit confusing.

Besides: the separating line does not appear when the abovementioned option is unchecked.

Theme: Revolution

**Comment by kimisgold** [comment]
I've replaced the red with the secondary gold accent. Does this look any better?

**Comment by DBinaghi** [comment]
Surely better, although gold is probably still a bit too brilliant, anything paler would be probably better.
