### ISSUE TITLE
Width of metadata column

### ISSUE THREAD

**Issue by DBinaghi** [omeka/theme-foundation-classic#29]
In Items/Show, there seems to be a maximum width set for metadata, although the same width does not apply to positioning of navigation buttons, for instance. A free width for metadata, so that they can fill the page, would look more natural.

**Comment by kimisgold** [comment]
This was partially due to mishandling of the single/double column layout setting, which should now be fixed. There is still a maximum width for readability purposes, but it is now wider within the single column layout.
