### ISSUE TITLE
Tags' label in Items/Browse

### ISSUE THREAD

**Issue by DBinaghi** [omeka/theme-foundation-classic#30]
Tags label in Items/Browse appears with a rectangular colourful background. In many sites, that's normally the aspect of a tag itself, and not of the field label.
Suggestion: label could have the same style of Items/Show one.

Theme: Revolution

**Comment by kimisgold** [comment]
That's a common pattern, but not my preference, as I feel it adds a lot of visual weight to the individual tags that can create some clutter. I also don't want the tags to get lost in possible long descriptions, so I think the current style on the tags label strikes a balance I'm comfortable with within the view's context.

**Comment by DBinaghi** [comment]
I agree. I meant I would remove the background from the TAGS label, and format it like you did in Items/Show.
