### ISSUE TITLE
Display Featured Exhibit config option only when plugin installed

### ISSUE THREAD

**Issue by DBinaghi** [omeka/theme-foundation-classic#35]
As Exhibit Builder is an optional plugin, I'd suggest for the config page to check whether that plugin is installed and active before showing the "Display Featured Exhibit" option (I would not take away the option, but rather it could be disabled and grayed out, if plugin was not installed/active, and description could say plugin is needed for that option to be enabled).

**Comment by kimisgold** [comment]
I've implemented a new setup for the featured section on the homepage. The user can now select what type of record to display in each of the featured areas, and the Exhibit Builder option falls back to text instructing to activate the plugin when it is not available.
