### ISSUE TITLE
Page messed up with Navigation Layout = Full Height Column

### ISSUE THREAD

**Issue by DBinaghi** [omeka/theme-foundation-classic#38]
Index page is messed up with Navigation Layout = Full Height Column:

![image](https://user-images.githubusercontent.com/39097246/113030882-59a06700-918e-11eb-8ef3-1e8a3bbbddf9.png)

**Comment by kimisgold** [comment]
I'm having trouble reproducing this. Could you tell me what plugins you have installed and what browser you're using?

**Comment by DBinaghi** [comment]
Hi.

I'm using Chrome.

As for the plugins, here's the list:
BulkMetadataEditor | 2.8 ; CSSEditor | 1.1 ; CSVExport | 1.3 ; ClickableLinksPlus | 1.2 ; CsvImportPlus | 2.3.3 ; DefaultSort | 1.3 ; Dropbox | 0.7.2 ; EmailNotification | 1.3 ; HideElements | 1.3 ; HideFiles | 1.0.1 ; HonorThyLibrarians | 1.1 ; ItemDuplicateCheck | 0.2.0 ; ItemDuplicator | 1.2.2 ; LimitVisibilityToOwn | 1.0 ; MoreMediaTypes | 1.3 ; MoreUserRoles | 1.0.2 ; Multilanguage | 1.6.0 ; PublicEditLink | 1.1.0 ; ReassignOwnership | 1.0 ; Reference | 2.6 ; SearchByMetadata | 1.2.1 ; SimpleContactForm | 0.6 ; SimplePages | 3.1.3 ; SimpleVocabPlus | 2.4 ; SocialBookmarking | 2.0.3 ; Stats | 2.2.4.1 ; WikipediaCitations | 1.1

Let me know if you want me to test the site while deactivating any of them.

Just tried to inspect the page, and removing `flex-flow: column wrap` seems to get the side menu to its side and (almost: search button end up between side menu and main content) everything to its place.

**Comment by lipeck** [comment]
just checking in to say i'm having this issue as well -- using the seafoam theme on Chrome.

**Comment by DBinaghi** [comment]
Updates: 
- tested disabling all plugins, issue remains the same (so, no plugin is to blame);
- tested with **Edge**, issue remains the same

**Comment by kimisgold** [comment]
I pushed a fix in https://github.com/omeka/theme-foundation-classic/commit/dfe633024783d2c4655e6877715f76501bf1e847. Could you check to see if there's any improvement?

**Comment by DBinaghi** [comment]
Improvement: yes. Solved: not yet...

The side menu stands correctly on the side, now. The search field is opened and at the top, with transparent background (not sure that's intentional, I'm just assuming it is). But the page is fixed and stuck: no footer visible, and no scrollbar visible, so one cannot scroll down the page.

[Revolution theme, on Chrome]

**Comment by kimisgold** [comment]
Ah, i was testing with short pages. Hopefully 1933382 addresses this latest issue.

**Comment by lipeck** [comment]
this fixed the issue for me!

**Comment by DBinaghi** [comment]
Fixed the issue for me too. Good job!
