### ISSUE TITLE
Test new media viewer 

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-foundation-classic#50]
I've just implemented the lightgallery jquery media viewer. It includes the following features:

* Support for still images and Html5 video
* Download links 
* One level of zoom in/out
* Fullscreen views
* Thumbnail pagers when multiple files are attached

It lives on the `lightgallery` branch and needs to be tested on mobile and desktop browsers. I'm also open to feature requests in feedback.

**Comment by katknow** [comment]
@kimisgold I'm afraid I may have gone wrong somewhere but am not sure where. I went into the theme then did git checkout lightgallery and it says it switched. When I click through any items on the front end I'm getting this screen: 

<img width="697" alt="Screen Shot 2021-08-30 at 2 01 35 PM" src="https://user-images.githubusercontent.com/84726696/131383889-cce271cc-79c6-4f7b-8bba-3a78bf7e82f7.png">

I checked and it seems I do have the error logging turned on but the log is empty. Cleared cache/did hard refresh nothing changed.

**Comment by katknow** [comment]
@kimisgold here's the error:


Omeka has encountered an error

Zend_Http_Client_Exception

    Passed parameter is not a valid HTTP URI.

Zend_Http_Client_Exception: Passed parameter is not a valid HTTP URI. in /var/www/html/katknow/OmekaTesting/application/libraries/Zend/Http/Client.php:318
Stack trace:
#0 /var/www/html/katknow/OmekaTesting/plugins/Scripto/libraries/Scripto/Service/MediaWiki.php(121): Zend_Http_Client->setUri(NULL)
#1 /var/www/html/katknow/OmekaTesting/plugins/Scripto/libraries/Scripto.php(82): Scripto_Service_MediaWiki->__construct(NULL, true, NULL)
#2 /var/www/html/katknow/OmekaTesting/plugins/Scripto/ScriptoPlugin.php(369): Scripto->__construct(Object(ScriptoAdapterOmeka), Array)
#3 /var/www/html/katknow/OmekaTesting/plugins/Scripto/ScriptoPlugin.php(294): ScriptoPlugin::getScripto()
#4 /var/www/html/katknow/OmekaTesting/plugins/Scripto/ScriptoPlugin.php(253): ScriptoPlugin->_appendToItemsShow()
#5 /var/www/html/katknow/OmekaTesting/application/libraries/Omeka/Plugin/Broker.php(154): ScriptoPlugin->hookPublicItemsShow(Array)
#6 /var/www/html/katknow/OmekaTesting/application/libraries/globals.php(188): Omeka_Plugin_Broker->callHook('public_items_sh...', Array)
#7 /var/www/html/katknow/OmekaTesting/themes/Foundation/items/show.php(52): fire_plugin_hook('public_items_sh...', Array)
#8 /var/www/html/katknow/OmekaTesting/application/libraries/Omeka/View.php(114): include('/var/www/html/k...')
#9 /var/www/html/katknow/OmekaTesting/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/var/www/html/k...')
#10 /var/www/html/katknow/OmekaTesting/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render(NULL)
#11 /var/www/html/katknow/OmekaTesting/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('items/show.php', NULL)
#12 /var/www/html/katknow/OmekaTesting/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#13 /var/www/html/katknow/OmekaTesting/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#14 /var/www/html/katknow/OmekaTesting/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#15 /var/www/html/katknow/OmekaTesting/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('showAction')
#16 /var/www/html/katknow/OmekaTesting/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#17 /var/www/html/katknow/OmekaTesting/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#18 /var/www/html/katknow/OmekaTesting/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#19 /var/www/html/katknow/OmekaTesting/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#20 /var/www/html/katknow/OmekaTesting/index.php(23): Omeka_Application->run()
#21 {main}

**Comment by kimisgold** [comment]
This seems to be related to Scripto. Can you deactivate it and see if you're still getting the error?

**Comment by katknow** [comment]
@kimisgold Just deactivated and seems to be working, thanks!

**Comment by katknow** [comment]
@kimisgold I'm able to get full page view on Chrome, Safari, Firefox, and Edge. However, I cannot get the zoom in/out feature to work on Safari. I can only get the download button to appear for videos on Chrome and in Edge (chrome tested both Mac & PC). I can't seem to get the thumbnail pager to appear, would that just be in the regular browse page or would I need to look in a different area? Hard refreshed and cleared cookies/cache on all browsers (know it did something because that's how I got the download button to appear for Chrome & Edge). Not having much luck with any of it on mobile browsers, but going to update my phone and see if that helps.

**Comment by katknow** [comment]
@kimisgold seems to work well across browsers on both desktop and mobile. Doesn't seem to have the same nav bar issues, but I do have to switch back to the master branch from new-admin-theme in order to add sub navigation to test. Don't know if that was somewhere in the slack thread and I missed it.

**Comment by kimisgold** [comment]
There was a navigation bug that I fixed just this morning. If you pull the latest changes on `new-admin-theme`, subnavigation should be configurable again.

**Comment by katknow** [comment]
@kimisgold Yep, that was it! Everything looks good.
