### ISSUE TITLE
Test banner setting

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-foundation-classic#52]
There is now a theme setting that allows users to select a banner image to appear across site views. In additional settings, they can control:

* the maximum height of the banner for both mobile and desktop widths
* whether to match the width to the content or window
* where to position the image within the banner container when the container ratio has a much greater width than height

This is on the `master` branch and should be tested on desktop and mobile browsers.

**Comment by katknow** [comment]
Works well across browsers on desktop, just has the same issue of not moving for mobile if a different size is input for mobile devices and remains fixed to top.

**Comment by katknow** [comment]
Re-tested on mobile with new image, everything seems to be working.
