### ISSUE TITLE
Foundation Theme Bug 

### ISSUE THREAD

**Issue by berndAz** [omeka/theme-foundation-classic#53]
Happens only with Foundation-theme, browsing a collection.
 
Notice: Undefined variable: truncateDescription in /var/www/omeka/themes/foundation/collections/show.php on line 57 Call Stack #TimeMemoryFunctionLocation 10.0000397184{main}( ).../index.php:0 20.02862339840Omeka_Application->run( ).../index.php:23 30.02862339840Omeka_Application->run( ).../Application.php:73 40.02862339840Zend_Application_Bootstrap_Bootstrap->run( ).../Application.php:384 50.02872339840Zend_Controller_Front->dispatch( ).../Bootstrap.php:105 60.02922361176Zend_Controller_Dispatcher_Standard->dispatch( ).../Front.php:954 70.02982402184CollectionsController->dispatch( ).../Standard.php:308 80.03532518712Zend_Controller_Action_HelperBroker->notifyPostDispatch( ).../Action.php:527 90.03542519456Zend_Controller_Action_Helper_ViewRenderer->postDispatch( ).../HelperBroker.php:277 100.03542519456Zend_Controller_Action_Helper_ViewRenderer->render( ).../ViewRenderer.php:972 110.03552519536Zend_Controller_Action_Helper_ViewRenderer->renderScript( ).../ViewRenderer.php:933 120.03552519536Omeka_View->render( ).../ViewRenderer.php:912 130.03552536128Omeka_View->_run( ).../Abstract.php:888 140.03582542864include( '/var/www/omeka/themes/foundation/collections/show.php' ).../View.php:114 ">Rückseite Zahlung an Baumeister: 1636, 1637,136

**Comment by berndAz** [comment]
I solve the issue for me by adding in file omeka/themes/foundation/collections/show.php  after line 5 the following line

$truncateDescription = (get_theme_option('truncate_body_property') !== null) ? get_theme_option('truncate_body_property') : 'full';

**Comment by Gilles-Lengy** [comment]
Ok ! Thank you.

**Comment by kimisgold** [comment]
Thank you for this fix. It will be included with attribution in the next release.
